spring:
  application:
    name: email-application
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
  data:
    cassandra:
      keyspace-name: 
      username: 
      password: 
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection: 
        connect-timeout: 10s
        init-query-timeoout: 10s

astra.db:
    id: 
    region: 
    keyspace: 
    application.token: 

datastax.astra:
    secure-connect-bundle: secure-connect.zip